<!DOCTYPE html>
<html>
<body>
<h1>Wen Yuan</h1>
<p> github: https://github.com/WendyyCat</p>
<p> email: yuanwen9510@pku.edu.cn </p>
<p> College of Computer Science and Technology, Jilin University. 2014-2018 </p>
<p> Center for Data Science, Academy for Advanced Interdisciplinary Studies, Peking University. 2018- </p>

</body>
</html>